[tool.poetry]
name = "resume-templates"
version = "0.1.0"
description = ""
authors = ["Adrian <adrian@rydeas.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyperclip = "^1.8.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
